name: Build CanFitMind iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: List Xcode version
        run: xcodebuild -version

      - name: Build app
        run: |
          xcodebuild -project CanFitMind.xcodeproj \
                     -scheme CanFitMind \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     CODE_SIGNING_ALLOWED=NO
